language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t alanstill/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true alanstill/docker-react npm run test

#Tell travis where to deploy our app
deploy:
 provider: elasticbeanstalk
 region: "eu-west-2"
 app: "docker-react"
 env: "DockerReact-env"
 # S3 bucket that the zipped up files will be sent to
 bucket_name: "elasticbeanstalk-eu-west-2-884443452210"
 bucket_path: "docker-react"
 on:
  branch: master
 # API keys are required to access AWS - set up via IAM AWS Console
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key:
  secure: "$AWS_SECRET"